#!/usr/bin/env python3
"""
Find links in knowledge files that haven't been downloaded as knowledge entries.

A link is "downloaded" if its URL matches a `source:` field in any knowledge file.
Outputs undownloaded links grouped by the file that references them.
"""

import os
import re
import sys
from pathlib import Path
from typing import Optional
from urllib.parse import urlparse

KNOWLEDGE_DIR = Path(__file__).parent / "knowledge"
OUTPUT_FILE = Path(__file__).parent / "knowledge" / "undownloaded-links.md"

# URLs from these domains are tweet/social links, not downloadable articles
SKIP_DOMAINS = {
    "x.com",
    "twitter.com",
    "t.co",
    "pic.twitter.com",
}

# URL regex — matches http(s):// URLs, stops at whitespace or markdown punctuation
URL_PATTERN = re.compile(r'https?://[^\s\)\]>,"\']+')

# YAML frontmatter source field
SOURCE_PATTERN = re.compile(r'^source:\s*["\']?(https?://[^\s"\']+)["\']?\s*$', re.MULTILINE)


def extract_frontmatter_source(content: str) -> Optional[str]:
    """Extract the `source:` URL from YAML frontmatter, if it's a full URL."""
    match = SOURCE_PATTERN.search(content)
    return match.group(1) if match else None


def normalize_url(url: str) -> str:
    """Strip trailing punctuation and fragments for comparison."""
    url = url.rstrip(".,;:!?)")
    # Remove fragment
    parsed = urlparse(url)
    return parsed._replace(fragment="").geturl()


def is_skip_domain(url: str) -> bool:
    """Return True if the URL is a social/tweet link we don't want to download."""
    try:
        host = urlparse(url).netloc.lower().lstrip("www.")
        return any(host == d or host.endswith("." + d) for d in SKIP_DOMAINS)
    except Exception:
        return False


def collect_all_sources(md_files: list[Path]) -> set[str]:
    """Collect all `source:` URLs from all knowledge files."""
    sources = set()
    for f in md_files:
        content = f.read_text(encoding="utf-8", errors="ignore")
        src = extract_frontmatter_source(content)
        if src:
            sources.add(normalize_url(src))
    return sources


def extract_links_from_file(path: Path) -> list[str]:
    """Extract all HTTP(S) URLs from a markdown file."""
    content = path.read_text(encoding="utf-8", errors="ignore")
    urls = URL_PATTERN.findall(content)
    return [normalize_url(u) for u in urls]


def main():
    if not KNOWLEDGE_DIR.exists():
        print(f"Error: {KNOWLEDGE_DIR} not found", file=sys.stderr)
        sys.exit(1)

    md_files = sorted(KNOWLEDGE_DIR.rglob("*.md"))
    # Exclude the output file itself if it exists
    md_files = [f for f in md_files if f.resolve() != OUTPUT_FILE.resolve()]

    print(f"Scanning {len(md_files)} knowledge files...")

    known_sources = collect_all_sources(md_files)
    print(f"Found {len(known_sources)} known source URLs")

    # Map: file path → list of undownloaded URLs
    undownloaded: dict[Path, list[str]] = {}
    seen_globally: set[str] = set()

    for f in md_files:
        links = extract_links_from_file(f)
        missing = []
        for url in links:
            if url in seen_globally:
                continue
            if is_skip_domain(url):
                continue
            if url in known_sources:
                continue
            seen_globally.add(url)
            missing.append(url)

        if missing:
            undownloaded[f] = missing

    total = sum(len(v) for v in undownloaded.values())
    print(f"Found {total} undownloaded links across {len(undownloaded)} files")

    # Write output
    lines = [
        "# Undownloaded Links",
        "",
        f"Links found in knowledge files that don't have a corresponding knowledge entry.",
        f"Generated by `find-undownloaded-links.py`. **{total} links** across **{len(undownloaded)} files**.",
        "",
    ]

    for f in sorted(undownloaded.keys()):
        rel = f.relative_to(Path(__file__).parent)
        lines.append(f"## {rel}")
        lines.append("")
        for url in undownloaded[f]:
            lines.append(f"- {url}")
        lines.append("")

    OUTPUT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written to {OUTPUT_FILE.relative_to(Path(__file__).parent)}")


if __name__ == "__main__":
    main()
